name: a_bunch_of_books
description: Tracker for reading 1000 books before kindergarten

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^2.13.1
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  sqlite3_flutter_libs: ^0.5.18
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  flutter_riverpod: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.13.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true